sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install
  - composer show

# Use /home/travis/.phpenv/shims/php as binary when using sudo,
# otherwise we end up with HHVM.

script:
  - sudo /home/travis/.phpenv/shims/php vendor/bin/phpunit --coverage-text
