sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install
  - composer show

before_script:
  - sudo setcap cap_net_raw+ep $(realpath $(which php))

script:
  - vendor/bin/phpunit --coverage-text
